module.exports = {
  layoutView: 'lHh Lpr lFf',
  layoutHeader: false,
  layoutHeaderVisible: false,
  layoutHeaderReveal: false,
  layoutHeaderElevated: false,
  layoutHeaderBordered: false,
  headerCustomClass: '',
  layoutLeftDrawer: false,
  layoutLeftDrawerVisible: false,
  layoutLeftDrawerBehavior: 'default',
  layoutLeftDrawerOverlay: false,
  layoutLeftDrawerElevated: false,
  layoutLeftDrawerBordered: false,
  layoutLeftDrawerShowIfAbove: false,
  leftDrawerCustomClass: '',
  leftDrawerWidth: 300,
  layoutRightDrawer: false,
  layoutRightDrawerVisible: false,
  layoutRightDrawerBehavior: 'default',
  layoutRightDrawerOverlay: false,
  layoutRightDrawerElevated: false,
  layoutRightDrawerBordered: false,
  layoutRightDrawerShowIfAbove: false,
  rightDrawerCustomClass: '',
  rightDrawerWidth: 300,
  pageContainerCustomClass: '',
  layoutFooter: false,
  layoutFooterVisible: false,
  layoutFooterReveal: false,
  layoutFooterElevated: false,
  layoutFooterBordered: false,
  footerCustomClass: '',
  injectDrawerOnScrolling: true,
  layoutBreadcrumbs: false,
  layoutBreadcrumbsElements: []
}
